src/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('category/', views.category_list, name='category_list'),
    path('tagged/', views.tag_list, name='tag_list'),

    path('category/<category_slug>/<slug>/', views.post_detail, name='post_detail'),
    path('category/<slug>/', views.post_list_by_category, name='post_list_by_category'),
    path('tagged/<slug>/', views.post_list_by_tag, name='post_list_by_tag'),
]

src/bukantutorial/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'), name='posts'),
    path('martor/', include('martor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/media_library/urls.py
from django.urls import path
from . import views

app_name = 'files'

urlpatterns = [
    
]

src/blog/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse

from media_library.models import Media
from martor.models import MartorField

class Tag(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True,max_length=200)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("blog:post_list_by_tag", kwargs={"slug":self.slug})

    class Meta:
        ordering = ['name']

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True,max_length=200)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("blog:post_list_by_category", kwargs={"slug":self.slug})
    
    class Meta:
        ordering = ['name']

class Post(models.Model):
    meta_description = models.TextField()
    meta_keyword = models.CharField(max_length=200)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True,max_length=200)
    content = MartorField(default="")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None, null=True, blank=True)
    created_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True)
    updated_date = models.DateTimeField(auto_now=True, auto_now_add=False)
    featured_image = models.ForeignKey(Media, on_delete=models.CASCADE, default=None, null=True, blank=True)
    tag = models.ManyToManyField(Tag)
    
    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={"slug": self.slug, "category_slug": self.category.slug})

    class Meta :
        ordering = ["-published_date"]

src/media_library/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.conf import settings

class Media(models.Model):
    name = models.CharField(max_length=150, blank=True, null=True)
    alt_text = models.CharField(max_length=150, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    file = models.FileField(upload_to='uploads/%Y/%m/')
    uploaded_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    upload_date = models.DateTimeField(auto_now_add=True)
    # caption = models.TextField(blank=True, null=True)
    # file_name = models.TextField()
    # file_type = models.CharField(max_length=150)
    # file_size = models.CharField(max_length=20)
    # dimension = models.CharField(max_length=150, blank=True, null=True)
    
    def __str__(self):
        return self.name

src/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    ''' 
    Create Custom user for further use later
    '''
    bio = models.CharField(max_length=250)
    
    def __str__(self):
        return self.username

src/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from .models import Post, Category, Tag

# tag func
def post_list_by_tag(request, slug):
    """
        Show all posts with specified tag in post_list.html
        if tag url wrong or tag not found then show 404
    """

    init_tag = get_object_or_404(Tag, slug=slug)
    get_posts = init_tag.post_set.filter(tag=init_tag, published_date__lte=timezone.now())
    paginator = Paginator(get_posts, 6) # Show n posts per page.
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)

    context = {
        'posts': posts,
    }
    return render(request, 'blog/post_list.html', context)

def tag_list(request):
    """
        Show all tags
    """
    tags = Tag.objects.all()
    context= {
        'tags': tags,
    }
    return render(request, 'blog/tag_list.html', context)

# category func
def post_list_by_category(request, slug):
    """
        Show all posts with specified category in post_list.html
        if category url wrong or category not found then show 404
    """
    # bisa juga pake ini doangan, cuman kalo categorynya gak ada dia nampilin kosongan bukan 404
    # posts = Post.objects.filter(category__slug=slug)
    
    init_category = get_object_or_404(Category, slug=slug)
    get_posts = init_category.post_set.filter(category=init_category, published_date__lte=timezone.now())
    paginator = Paginator(get_posts, 6) # Show n posts per page.
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)

    context = {
        'posts': posts,
    }
    return render(request, 'blog/post_list.html', context)

def category_list(request):
    """
        Show all categories
    """
    categories = Category.objects.all()
    context= {
        'categories': categories,
    }
    return render(request, 'blog/category_list.html', context)

# post func
def post_list(request):
    """
        Show all published posts in post_list.html
    """
    get_posts = Post.objects.filter(published_date__lte=timezone.now())

    # search
    search = request.GET.get("search")
    if search:
        get_posts = get_posts.filter(
            Q(title__icontains=search) |
            Q(content__icontains=search)
            )
    
    paginator = Paginator(get_posts, 6) # Show n posts per page.
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    context= {
        'posts': posts,
    }
    
    return render(request, 'blog/post_list.html', context)

def post_detail(request, slug, category_slug):
    """
        Show detail published post in post_detail.html
        if post url wrong or post not found then show 404
    """
    post = get_object_or_404(Post, slug=slug)
    context = {
        'post': post,
    }
    return render(request, 'blog/post_detail.html', context)

src/media_library/views.py
from django.shortcuts import render

# Create your views here.

src/users/views.py
from django.shortcuts import render

# Create your views here.

src/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    {% url 'posts:post_list' as the_url %}
    {% if request.get_full_path != the_url %}
    <meta name="description" content="{% block description %} {% endblock%}">
    <meta name="keywords" content="{% block keyword %} {% endblock%}">
    <title>{% block title %}{% endblock %}</title>
    {% else %}
    <meta name="description" content="Ini bukan tutorial yahh">
    <meta name="keywords" content="django, bootstrap, jquery, javascript, css, free template">
    <title>Bukan Tutorial</title>
    {% endif %}
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;700&display=swap" rel="stylesheet">
    <!-- Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'css/normalize.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/styles/vs.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body onload="getHighest()">
    <header>
        <div class="navbar-wrapper clearfix" id="navbar">
            <div class="logo">
                <a href="{% url 'blog:post_list' %}">BUKAN</a>
            </div>
            <div class="navbar-menu">
                <a href="#home">Home</a>
                <a href="#news">News</a>
                <a href="#contact">Contact</a>
                <a href="#about">About</a>
                <div id="search-top">
                    <form action="">
                        <input type="text" placeholder="Search.." name="search">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </div>
            </div>
            <a href="javascript:void(0);" class="icon" onclick="myFunction()">
                <i class="fa fa-bars"></i>
            </a>

        </div>
    </header>
    <section id="main">
        <div class="container">
            <div class="row clearfix">
                <!-- all post -->
                <div class="col-9 col-md-12">
                    <div class="post-wrapper clearfix">
                        {% block main_content %}
                        {% endblock %}
                    </div>
                </div>
                {% include 'blog/sidebar.html' %}
                {% block sidebar %}
                {% endblock %}
            </div>
        </div><!-- End Container -->
    </section>


    <script>
        function myFunction() {
            var navbar = document.getElementById("navbar");
            var searchTop = document.getElementById("search-top")
            if (navbar.className === "navbar-wrapper clearfix") {
                navbar.className += " responsive";
                searchTop.style.display = "block";
            } else {
                navbar.className = "navbar-wrapper clearfix";
                searchTop.style.display = "none";
            }
        }

        function getHighest() {
            var i;
            var elmntListHeight = []
            var getElmnt = document.getElementsByClassName("artikel-info");
            for (i = 0; i < getElmnt.length; i++) {
                elmntListHeight.push(getElmnt[i].offsetHeight);
            }
            var maxHeight = Math.max(...elmntListHeight)
            for (i = 0; i < elmntListHeight.length; i++) {
                getElmnt[i].style.height = String(maxHeight - 30) + "px";
            }

        }
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"></script>
    <script>
        hljs.initHighlightingOnLoad();
    </script>
</body>

</html>

src/blog/templates/blog/category_list.html
{% extends 'blog/base.html' %}

{% block main_content %}
    <div class="categories">
        <h1>Category lists : </h1>
    </div>
    {% for category in categories %}
    <div class="col-12 col-md-12">
        <div class="artikel">
            <div class="artikel-info">
                <h1 class="h1-list-post"><a href="{{ category.get_absolute_url }}">{{ category.name }}</a></h1>
            </div>
        </div>
    </div>
	{% endfor %}
{% endblock %}

src/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}


{% block description %}{{ post.meta_description }}{% endblock %}
{% block keyword %}{{ post.meta_keyword }}{% endblock %}
{% block title %}Bukan Tutorial | {{ post.title }}{% endblock %}

{% block main_content %}
<div class="col-12">
    <div class="breadcrumb-wrapper">
        <ul class="breadcrumb">
            <li>
                <a href="{% url 'blog:post_list' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'blog:post_list_by_category' slug=post.category.slug %}">Category</a>
            </li>
            <li>
                <a href="{{ post.category.get_absolute_url }}">{{ post.category.name }}</a>
            </li>
            <li>{{ post.title }}</li>
        </ul>
    </div>
</div>
<div class="col-12 post-detail-wrapper">
    <div class="artikel">
        <div class="feature-image">
            <img class="img-responsive" src="{{ post.featured_image.file.url }}">
        </div>
        <div class="artikel-info">
            <div class="post-title">
                <h1 class="h1-detail-post">{{ post.title }}</h1>
            </div>
            <div class="post-meta clearfix">
                <p class="nomargin-top">{{ post.published_date|date:"M d, Y" }}</p>
                <p class="nomargin-top">
                    <a class="btn btn-custom" href="{{ post.category.get_absolute_url }}">{{ post.category.name }}</a>
                </p>
            </div><!-- /post-meta-->
            <div class="post-content">
                {% load martortags %}
                <p>{{ post.content|safe_markdown }}</p>
            </div><!-- /isi-artikel -->
            <div class="tagged">
                </br>
                <p>Tags : </p>
                <p>
                    {% for tag in post.tag.all %}
                        <a class="btn btn-tags-item" href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                    {% endfor %}
                </p>
            </div>
        </div>
    </div>
</div>


{% endblock %}

src/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block main_content %}
{% if posts %}
    {% for post in posts %}
    <div class="col-6 col-md-12 post-list">
        <div class="artikel">
            <div class="post-thumbnail">
                <img class="img-responsive" src="{{ post.featured_image.file.url }}">
            </div><!-- /post-thumbnail -->

            <div class="artikel-info">
                <div class="post-title">
                    <h1 class="h1-list-post"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                </div><!-- /post-title -->

                <div class="post-meta clearfix">
                    <p class="nomargin-top">{{ post.published_date|date:"M d, Y" }}</p>
                    <p class="nomargin-top">
                        <a class="btn btn-custom" href="{{ post.category.get_absolute_url }}">{{ post.category.name }}</a>
                    </p>
                </div><!-- /post-meta-->
                <div class="post-content">
                    {{ post.content|truncatewords:30 }}
                </div><!-- /isi-artikel -->
            </div>

        </div><!-- /artikel -->
    </div>
    {% endfor %}
{% else %}
<div class="col-12">
    <h1>"not found"</h1>
</div>
{% endif %}

{% if posts.has_other_pages %}
<div class="col-12 pagination">
        {% for i in posts.paginator.page_range %}
            {% if posts.number == i %}
                {% if posts.has_previous and posts.has_next  %}
                <ul>
                    <li>
                        <a href="?page={{ posts.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">Previous</a>
                    </li>
                    <li>
                        <a href="?page={{ i|add:-1 }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ i|add:-1 }}</a>
                    </li>
                    <li class="active">
                        <span>{{ i }}</span></li>
                    </li>
                    <li>
                        <a href="?page={{ i|add:1 }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ i|add:1 }}</a>
                    </li>
                    <li>
                        <a href="?page={{ posts.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">Next</a>
                    </li>
                </ul>

                {% elif posts.has_previous and not posts.has_next  %}
                <ul>
                    <li>
                        <a href="?page={{ posts.previous_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">Previous</a>
                    </li>
                    {% if posts.paginator.num_pages > 2 %}
                    <li>
                        <a href="?page={{ i|add:-2 }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ i|add:-2 }}</a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="?page={{ i|add:-1 }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ i|add:-1 }}</a>
                    </li>
                    <li class="active">
                        <span>{{ i }}</span></li>
                    </li>
                </ul>
                
                {% else %}
                <ul>
                    <li class="active">
                        <span>{{ i }}</span></li>
                    </li>
                    <li>
                        <a href="?page={{ i|add:1 }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ i|add:1 }}</a>
                    </li>
                    {% if posts.paginator.num_pages > 2 %}
                    <li>
                        <a href="?page={{ i|add:2 }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">{{ i|add:2 }}</a>
                    </li>
                    {% endif %}
                    <li>
                        <a href="?page={{ posts.next_page_number }}{% if request.GET.search %}&search={{ request.GET.search }}{% endif %}">Next</a>
                    </li>
                </ul>
                {% endif %}
            {% endif %}
        {% endfor %}

</div>
{% endif %}
{% endblock %}

src/blog/templates/blog/sidebar.html
{% block sidebar %}
    <!-- sidebar -->
    <div class="col-3 col-md-12">
        <div class="side-bar">
            <div class="side-bar-item">
                <div class="search">
                    <form method="GET" action="{% url 'blog:post_list' %}">
                        <input type="text" placeholder="Search.." name="search" value="{{ request.GET.search }}">
                        <button type="submit"><i class="fa fa-search"></i></button>
                    </form>
                </div>
                <div class="recent-post">
                    <div class="title-side-bar-item">
                        <h4>Recent Post</h4>
                    </div>
                    <div class="recent-post-item">
                        {% for recent in recent_posts %}
                            <p><a href="{{ recent.get_absolute_url }}">{{ recent.title }}</a></p>
                        {% endfor %}
                    </div>
                </div>
                <div class="category">
                    <div class="title-side-bar-item">
                        <h4>Category</h4>
                    </div>
                    <div class="category-item">
                        {% for category in categories_sidebar %}
                            <p><a href="{{ category.get_absolute_url }}">{{ category.name }} ( {{ category.counter }} )</a></p>
                        {% endfor %}
                    </div>
                </div>
                <div class="tags">
                    <div class="title-side-bar-item">
                        <h4>Tags</h4>
                    </div>
                    <div class="tags-item">
                        <p>
                            {% for tag in tags_sidebar %}
                                <a class="btn btn-tags-item" href="{{ tag.get_absolute_url }}">{{ tag.name }}</a>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/blog/templates/blog/tag_list.html
{% extends 'blog/base.html' %}

{% block main_content %}
    <div class="categories tags">
        <h1>Tags : </h1>
    </div>
    {% for tag in tags %}
    <div class="col-12 col-md-12">
        <div class="artikel">
            <div class="artikel-info">
                <h1 class="h1-list-post"><a href="{{ tag.get_absolute_url }}">{{ tag.name }}</a></h1>
            </div>
        </div>
    </div>
	{% endfor %}
{% endblock %}